// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RecTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  private WebDriverWait wait;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    WebDriverWait wait = new WebDriverWait(driver,10);
  }
  /*@After
  public void tearDown() {
    driver.quit();
  }*/
  @Test
  public void rec() {
    driver.get("https://crm.topnlab.ru/authorize/login");
    driver.manage().window().setSize(new Dimension(1288, 816));
    driver.findElement(By.name("email")).sendKeys("s.evgeniy@topnlab.ru");
    driver.findElement(By.name("password")).sendKeys("54255425");
    driver.findElement(By.xpath("//button[contains(., 'Войти' )]")).click();
    WebElement dynamicElement = (new WebDriverWait(driver, 10))
            .until(ExpectedConditions.presenceOfElementLocated(By.xpath("//li[contains(., 'Объекты')]")));
    driver.findElement(By.xpath("//li[contains(., 'Объекты')]")).click();
    
    driver.findElement(By.xpath("//a[contains(., ' Продавцы ' )]")).click();
    driver.findElement(By.id("realty-create-button")).click();
    driver.findElement(By.cssSelector("#realty-create-button-dropdown > .item:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".modal__row:nth-child(2) .modal__field")).click();
    driver.findElement(By.cssSelector(".modal__cell > .ng-dirty")).sendKeys("тест");
    driver.findElement(By.cssSelector("#aboutRealtyPart_Realty_acc .title-wrap")).click();
    driver.findElement(By.cssSelector("#price .modal__field")).click();
    driver.findElement(By.cssSelector(".ui > .ng-dirty")).sendKeys("123");
    driver.findElement(By.cssSelector("#serviceFieldsPart_Realty_acc .title-wrap")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector("#serviceFieldsPart_Realty > .modal__row .modal__field")).click();
    driver.findElement(By.cssSelector(".modal__cell > .modal__field:nth-child(2)")).sendKeys("12");
    driver.findElement(By.cssSelector(".mr-0")).click();
    driver.findElement(By.cssSelector(".modal__btn-block > .\\_red")).click();
  }
}
