// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class TestCRM {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("https://crm.topnlab.ru/authorize/login");
    driver.manage().window().setSize(new Dimension(1288, 816));
    driver.findElement(By.name("email")).sendKeys("s.evegniy@topnlab.ru");
    driver.findElement(By.name("password")).sendKeys("54255425");
    driver.findElement(By.cssSelector(".login")).click();
    {
      WebElement element = driver.findElement(By.name("email"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.name("email"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.name("email"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("s.evgeniy@topnlab.ru");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("Продавцы")).click();
    {
      WebElement element = driver.findElement(By.linkText("Продавцы"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("realty-create-button")).click();
    driver.findElement(By.cssSelector(".item:nth-child(1) > .chat-item__source")).click();
    driver.findElement(By.cssSelector(".modal__row:nth-child(2) .modal__field")).click();
    driver.findElement(By.cssSelector(".modal__cell > .ng-dirty")).sendKeys("тест");
    driver.findElement(By.cssSelector("#aboutRealtyPart_Realty_acc .title-wrap")).click();
    driver.findElement(By.cssSelector("#price .modal__field")).click();
    driver.findElement(By.cssSelector(".ui > .ng-dirty")).sendKeys("12");
    driver.findElement(By.id("serviceFieldsPart_Realty_acc")).click();
    driver.findElement(By.cssSelector("#serviceFieldsPart_Realty_acc .title-wrap")).click();
    driver.findElement(By.cssSelector("#serviceFieldsPart_Realty > .modal__row .modal__field")).click();
    driver.findElement(By.cssSelector(".modal__cell > .modal__field:nth-child(2)")).sendKeys("12");
    driver.findElement(By.cssSelector(".mr-0")).click();
    driver.findElement(By.cssSelector(".modal__btn-block > .\\_red")).click();
  }
}
